{
    "openapi": "3.0.1",
    "info": {
        "title": "Core Content Business Object Service",
        "version": "1.0"
    },
    "servers": [
        {
            "url": "https://na-1-dev.api.opentext.com/ccbo",
            "description": "Build & Test"
        },
        {
            "url": "https://na-1.api.opentext.com/ccbo",
            "description": "NA Production"
        }
    ],
    "security": [
        {
            "tenant": []
        }
    ],
    "paths": {
        "/api/v1/businessworkspaces": {
            "put": {
                "tags": [
                    "business-object-controller"
                ],
                "summary": "Creates or updates workspaces.",
                "operationId": "createOrUpdateWorkspaces_1",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/CreateorUpdateWorkspaceBody"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/CreateOrUpdateWorkspaceResult"
                                    }
                                }
                            },
                            "application/hal+json": {
                                "schema": {
                                    "oneOf": [
                                        {
                                            "$ref": "#/components/schemas/CollectionModelCreateOrUpdateWorkspaceResult"
                                        },
                                        {
                                            "$ref": "#/components/schemas/CollectionModel"
                                        }
                                    ]
                                }
                            }
                        }
                    },
                    "207": {
                        "description": "Multi-Status",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/CreateOrUpdateWorkspaceResult"
                                    }
                                }
                            },
                            "application/hal+json": {
                                "schema": {
                                    "$ref": "#/components/schemas/CollectionModel"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "all failures": {
                                        "description": "No workspaces were created or updated",
                                        "value": [
                                            {
                                                "objectId": "SFDemo1",
                                                "status": {
                                                    "errors": [
                                                        "objectType \"NoSuchType\" not found."
                                                    ]
                                                }
                                            }
                                        ]
                                    }
                                }
                            },
                            "application/hal+json": {
                                "examples": {
                                    "all failures": {
                                        "description": "No workspaces were created or updated",
                                        "value": {
                                            "content": [
                                                {
                                                    "objectId": "SFDemo1",
                                                    "status": {
                                                        "errors": [
                                                            "objectType \"NoSuchType\" not found."
                                                        ]
                                                    }
                                                }
                                            ],
                                            "_links": {
                                                "self": {
                                                    "href": "http://localhost:8070/api/v1/businessworkspaces"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/businessworkspaces/ids": {
            "post": {
                "tags": [
                    "business-object-controller"
                ],
                "summary": "Get workspace node ids for the given external system.",
                "operationId": "getWorkspaceNodeIds_1",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/GetWorkspaceNodeIdsBody"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            },
                            "application/hal+json": {
                                "schema": {
                                    "oneOf": [
                                        {
                                            "$ref": "#/components/schemas/CollectionModelString"
                                        },
                                        {
                                            "$ref": "#/components/schemas/CollectionModel"
                                        }
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/admin/boconfigs": {
            "get": {
                "tags": [
                    "business-object-controller"
                ],
                "summary": "Fetch the known business object configurations",
                "operationId": "getBoconfigs_1",
                "parameters": [
                    {
                        "name": "filter",
                        "in": "query",
                        "description": "Simple filter to select boconfig based on a field value.  It is currently limited to the form:<br><blockquote>field (eq|ne) 'literal-value'</blockquote>for example<br><blockquote>workspaceType eq 's4_bo_type_xyz12'</blockquote>",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/BoConfig"
                                    }
                                }
                            },
                            "application/hal+json": {
                                "schema": {
                                    "oneOf": [
                                        {
                                            "$ref": "#/components/schemas/CollectionModelBoConfigHal"
                                        },
                                        {
                                            "$ref": "#/components/schemas/CollectionModel"
                                        }
                                    ]
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "example": {
                                    "timestamp": "2021-08-30T16:56:17.682+00:00",
                                    "status": 400,
                                    "error": "Bad Request",
                                    "message": "bad filter syntax",
                                    "path": "/api/v1/admin/boconfigs"
                                }
                            },
                            "application/hal+json": {
                                "example": {
                                    "timestamp": "2021-08-30T16:56:17.682+00:00",
                                    "status": 400,
                                    "error": "Bad Request",
                                    "message": "bad filter syntax",
                                    "path": "/api/v1/admin/boconfigs"
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "business-object-controller"
                ],
                "summary": "Add or update a business object configuration",
                "description": "The \"businessObjectConfigName\" element uniquely identifies the boconfig.  Characters that are invalid in that value include: %, ', /, \\\\, and ;.",
                "operationId": "putBoconfig_1",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "string"
                            },
                            "example": {
                                "version": 2,
                                "externalSystem": "string",
                                "externalBusinessObjectType": "string",
                                "businessObjectConfigName": "string",
                                "businessObjectConfigLabel": null,
                                "workspaceType": "string",
                                "workspaceTypeTemplate": [
                                    {
                                        "condition": "string",
                                        "templateId": "string"
                                    }
                                ],
                                "workspaceNaming": "string",
                                "adapterName": "string",
                                "adapterInfo": null,
                                "attributeMappingOverride": [
                                    {
                                        "WorkspaceAttribute": "string",
                                        "BusinessObjectAttribute": "string",
                                        "BusinessAttributeType": "string"
                                    }
                                ],
                                "relationSelection": [
                                    {
                                        "property": "string",
                                        "relationDefinition": "string"
                                    }
                                ],
                                "relationDefinitions": [
                                    {
                                        "name": "string",
                                        "referenceBO": "string",
                                        "type": "parent"
                                    }
                                ],
                                "roleMapping": [
                                    {
                                        "condition": "string",
                                        "workspaceRole": "string",
                                        "remoteRole": [
                                            "string"
                                        ]
                                    }
                                ]
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/BoConfig"
                                }
                            },
                            "application/hal+json": {
                                "schema": {
                                    "$ref": "#/components/schemas/BoConfigHal"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "example": {
                                    "timestamp": "2021-08-30T11:32:05.986+00:00",
                                    "status": 400,
                                    "error": "Bad Request",
                                    "message": "Missing or invalid elements: [workspaceType]",
                                    "path": "/api/v1/admin/boconfigs"
                                }
                            },
                            "application/hal+json": {
                                "example": {
                                    "timestamp": "2021-08-30T11:32:05.986+00:00",
                                    "status": 400,
                                    "error": "Bad Request",
                                    "message": "Missing or invalid elements: [workspaceType]",
                                    "path": "/api/v1/admin/boconfigs"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/admin/boconfigs/{businessObjectConfigName}": {
            "get": {
                "tags": [
                    "business-object-controller"
                ],
                "summary": "Fetch the specified business object configuration.",
                "operationId": "getBoconfig_1",
                "parameters": [
                    {
                        "name": "businessObjectConfigName",
                        "in": "path",
                        "description": "Case-sensitive name of the business object configuration.",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/BoConfig"
                                }
                            },
                            "application/hal+json": {
                                "schema": {
                                    "$ref": "#/components/schemas/BoConfigHal"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "content": {
                            "application/json": {
                                "example": {
                                    "timestamp": "2021-08-30T11:39:24.029+00:00",
                                    "status": 404,
                                    "error": "Not Found",
                                    "message": "No boconfig named waha",
                                    "path": "/api/v1/admin/boconfigs/waha"
                                }
                            },
                            "application/hal+json": {
                                "example": {
                                    "timestamp": "2021-08-30T11:39:24.029+00:00",
                                    "status": 404,
                                    "error": "Not Found",
                                    "message": "No boconfig named waha",
                                    "path": "/api/v1/admin/boconfigs/waha"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "business-object-controller"
                ],
                "summary": "Remove the specified business object configuration",
                "operationId": "deleteBoconfig_1",
                "parameters": [
                    {
                        "name": "businessObjectConfigName",
                        "in": "path",
                        "description": "Case-sensitive name of the business object configuration.",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "BoInfoProperty": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "value": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            },
            "BusinessObject": {
                "type": "object",
                "properties": {
                    "objectId": {
                        "type": "string"
                    },
                    "objectType": {
                        "type": "string"
                    }
                }
            },
            "BusinessObjectInfo": {
                "type": "object",
                "properties": {
                    "objectId": {
                        "type": "string"
                    },
                    "objectType": {
                        "type": "string"
                    },
                    "objectURL": {
                        "type": "string"
                    },
                    "properties": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/BoInfoProperty"
                        }
                    },
                    "propertyGroups": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/PropertyGroup"
                        }
                    },
                    "relations": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/Relation"
                        }
                    },
                    "rolesUsers": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/RolesUser"
                        }
                    },
                    "propertiesMap": {
                        "type": "object",
                        "additionalProperties": {
                            "$ref": "#/components/schemas/BoInfoProperty"
                        }
                    },
                    "propertyGroupsMap": {
                        "type": "object",
                        "additionalProperties": {
                            "$ref": "#/components/schemas/PropertyGroup"
                        }
                    }
                }
            },
            "CreateorUpdateWorkspaceBody": {
                "type": "object",
                "properties": {
                    "businessObjectsInfo": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/BusinessObjectInfo"
                        }
                    }
                }
            },
            "PropertyGroup": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "properties": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/BoInfoProperty"
                        }
                    },
                    "propertiesMap": {
                        "type": "object",
                        "additionalProperties": {
                            "$ref": "#/components/schemas/BoInfoProperty"
                        }
                    }
                }
            },
            "Relation": {
                "type": "object",
                "properties": {
                    "relationType": {
                        "type": "string"
                    },
                    "businessObjects": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/BusinessObject"
                        }
                    }
                }
            },
            "RolesUser": {
                "type": "object",
                "properties": {
                    "role": {
                        "type": "string"
                    },
                    "users": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "groups": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            },
            "CreateOrUpdateWorkspaceResult": {
                "type": "object",
                "properties": {
                    "objectId": {
                        "type": "string"
                    },
                    "workspaceId": {
                        "type": "string"
                    },
                    "status": {
                        "type": "object",
                        "additionalProperties": {
                            "type": "object"
                        }
                    }
                }
            },
            "CollectionModel": {
                "type": "object",
                "properties": {
                    "_embedded": {
                        "type": "object",
                        "properties": {
                            "objects": {
                                "type": "array",
                                "items": {
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "_links": {
                        "$ref": "#/components/schemas/Links"
                    }
                }
            },
            "Links": {
                "type": "object",
                "additionalProperties": {
                    "$ref": "#/components/schemas/Link"
                }
            },
            "CollectionModelCreateOrUpdateWorkspaceResult": {
                "type": "object",
                "properties": {
                    "_embedded": {
                        "type": "object",
                        "properties": {
                            "createOrUpdateWorkspaceResults": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/components/schemas/CreateOrUpdateWorkspaceResult"
                                }
                            }
                        }
                    },
                    "_links": {
                        "$ref": "#/components/schemas/Links"
                    }
                }
            },
            "GetWorkspaceNodeIdsBody": {
                "type": "object",
                "properties": {
                    "businessObjects": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/BusinessObject"
                        }
                    }
                }
            },
            "CollectionModelString": {
                "type": "object",
                "properties": {
                    "_embedded": {
                        "type": "object",
                        "properties": {
                            "strings": {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "_links": {
                        "$ref": "#/components/schemas/Links"
                    }
                }
            },
            "AttributeMapping": {
                "type": "object",
                "properties": {
                    "WorkspaceAttribute": {
                        "type": "string"
                    },
                    "BusinessObjectAttribute": {
                        "type": "string"
                    },
                    "BusinessAttributeType": {
                        "type": "string"
                    }
                }
            },
            "BORelationDefinition": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "referenceBO": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string",
                        "enum": [
                            "parent",
                            "child",
                            "ibo"
                        ]
                    }
                }
            },
            "BORelationSelect": {
                "type": "object",
                "properties": {
                    "property": {
                        "type": "string"
                    },
                    "relationDefinition": {
                        "type": "string"
                    }
                }
            },
            "BORoleMapping": {
                "type": "object",
                "properties": {
                    "condition": {
                        "type": "string"
                    },
                    "workspaceRole": {
                        "type": "string"
                    },
                    "remoteRole": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            },
            "BoConfig": {
                "type": "object",
                "properties": {
                    "version": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "externalSystem": {
                        "type": "string"
                    },
                    "externalBusinessObjectType": {
                        "type": "string"
                    },
                    "businessObjectConfigName": {
                        "type": "string"
                    },
                    "businessObjectConfigLabel": {
                        "$ref": "#/components/schemas/ConfigLabel"
                    },
                    "workspaceType": {
                        "type": "string"
                    },
                    "workspaceTypeTemplate": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/WorkspaceTemplate"
                        }
                    },
                    "workspaceNaming": {
                        "type": "string"
                    },
                    "adapterName": {
                        "type": "string"
                    },
                    "adapterInfo": {
                        "$ref": "#/components/schemas/JsonNode"
                    },
                    "attributeMappingOverride": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/AttributeMapping"
                        }
                    },
                    "relationSelection": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/BORelationSelect"
                        }
                    },
                    "relationDefinitions": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/BORelationDefinition"
                        }
                    },
                    "roleMapping": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/BORoleMapping"
                        }
                    }
                }
            },
            "ConfigLabel": {
                "type": "object",
                "description": "A set of name-value pairs where the name is the lanugage and the value is the label for that language"
            },
            "JsonNode": {
                "type": "object"
            },
            "WorkspaceTemplate": {
                "type": "object",
                "properties": {
                    "condition": {
                        "type": "string"
                    },
                    "templateId": {
                        "type": "string"
                    }
                }
            },
            "BoConfigHal": {
                "type": "object",
                "properties": {
                    "content": {
                        "$ref": "#/components/schemas/BoConfig"
                    },
                    "_links": {
                        "$ref": "#/components/schemas/Links"
                    }
                }
            },
            "CollectionModelBoConfigHal": {
                "type": "object",
                "properties": {
                    "_embedded": {
                        "type": "object",
                        "properties": {
                            "boConfigHals": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/components/schemas/BoConfigHal"
                                }
                            }
                        }
                    },
                    "_links": {
                        "$ref": "#/components/schemas/Links"
                    }
                }
            },
            "Link": {
                "type": "object",
                "properties": {
                    "href": {
                        "type": "string"
                    },
                    "hreflang": {
                        "type": "string"
                    },
                    "title": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string"
                    },
                    "deprecation": {
                        "type": "string"
                    },
                    "profile": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "templated": {
                        "type": "boolean"
                    }
                }
            }
        },
        "securitySchemes": {
            "tenant": {
                "type": "openIdConnect",
                "openIdConnectUrl": "https://na-1-dev.api.opentext.com/tenants/$tenantId/.well-known/openid-configuration/"
            }
        }
    }
}